### ISSUE TITLE
Maintained?  Does not build with GHC 8.4 or higher

### ISSUE THREAD

**Issue by andreasabel** [nedervold/context-free-grammar#1]
Is this project still maintained?

The last GHC version it builds with is 8.2.  From 8.4, we see this error:
```
src/Data/Cfg/Cfg.hs:78:54: error:
    Ambiguous occurrence ‘<>’
    It could refer to either ‘Prelude.<>’,
                             imported from ‘Prelude’ at src/Data/Cfg/Cfg.hs:6:8-19
                             (and originally defined in ‘GHC.Base’)
                          or ‘Text.PrettyPrint.<>’,
                             imported from ‘Text.PrettyPrint’ at src/Data/Cfg/Cfg.hs:32:1-23
                             (and originally defined in ‘Text.PrettyPrint.HughesPJ’)
   |
78 |                         pv (NT hd), text "::=", rhs' <> text "."]
```

**Comment by nedervold** [comment]
Sorry for the delayed response.  No, I haven't used this code in a long time, but I'm happy it's presumably been of use to you.  I'll take a look at your changes but life is busy and it might take me a week or so.

**Comment by andreasabel** [comment]
No problem.
If you want help, you can add me to the maintainers: https://hackage.haskell.org/user/AndreasAbel
I could upload the fixed version to hackage.
