### PR TITLE
Fix #1: compile with ghc >= 8.4

### LINKED ISSUE #1: Maintained?  Does not build with GHC 8.4 or higher
Is this project still maintained?

The last GHC version it builds with is 8.2.  From 8.4, we see this error:
```
src/Data/Cfg/Cfg.hs:78:54: error:
    Ambiguous occurrence ‘<>’
    It could refer to either ‘Prelude.<>’,
                             imported from ‘Prelude’ at src/Data/Cfg/Cfg.hs:6:8-19
                             (and originally defined in ‘GHC.Base’)
                          or ‘Text.PrettyPrint.<>’,
                             imported from ‘Text.PrettyPrint’ at src/Data/Cfg/Cfg.hs:32:1-23
                             (and originally defined in ‘Text.PrettyPrint.HughesPJ’)
   |
78 |                         pv (NT hd), text "::=", rhs' <> text "."]
```

### PR DESCRIPTION
**Pull request by andreasabel**
Fix #1: compile with ghc >= 8.4

Also:
- tabs to spaces
- CI on github actions generated by haskell-ci

### CODE REVIEW

**Comment by andreasabel** [comment]
Tests passed, see https://github.com/andreasabel/context-free-grammar/actions/runs/758443399.

**Comment by andreasabel** [comment]
The actual fix is in bc9aa40c04d95b1ad4efb4d3225081cbfcde2307, which sorts out the `Semigroup` issue.

**Review by nedervold — APPROVED** [review]

**Review by nedervold — APPROVED** [review]

**Review by nedervold — APPROVED** [review]

**Review by nedervold — APPROVED** [review]
